package com.supcoder.hub.db.dao;

import com.supcoder.hub.db.domain.ApiKeys;
import com.supcoder.hub.db.domain.ApiKeysExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ApiKeysMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api_keys
     *
     * @mbg.generated
     */
    long countByExample(ApiKeysExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api_keys
     *
     * @mbg.generated
     */
    int deleteByExample(ApiKeysExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api_keys
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer keyId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api_keys
     *
     * @mbg.generated
     */
    int insert(ApiKeys record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api_keys
     *
     * @mbg.generated
     */
    int insertSelective(ApiKeys record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api_keys
     *
     * @mbg.generated
     */
    ApiKeys selectOneByExample(ApiKeysExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api_keys
     *
     * @mbg.generated
     */
    ApiKeys selectOneByExampleSelective(@Param("example") ApiKeysExample example, @Param("selective") ApiKeys.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api_keys
     *
     * @mbg.generated
     */
    List<ApiKeys> selectByExampleSelective(@Param("example") ApiKeysExample example, @Param("selective") ApiKeys.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api_keys
     *
     * @mbg.generated
     */
    List<ApiKeys> selectByExample(ApiKeysExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api_keys
     *
     * @mbg.generated
     */
    ApiKeys selectByPrimaryKeySelective(@Param("keyId") Integer keyId, @Param("selective") ApiKeys.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api_keys
     *
     * @mbg.generated
     */
    ApiKeys selectByPrimaryKey(Integer keyId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api_keys
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ApiKeys record, @Param("example") ApiKeysExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api_keys
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ApiKeys record, @Param("example") ApiKeysExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api_keys
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ApiKeys record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api_keys
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ApiKeys record);
}