# 基础镜像
FROM  openjdk:8-jre
# author
MAINTAINER supcoder

# 挂载目录
VOLUME /home/supcoder
# 创建目录
RUN mkdir -p /home/supcoder
# 指定路径
WORKDIR /home/supcoder
# 复制jar文件到路径
COPY ./jar/supcoder-gateway.jar /home/supcoder/supcoder-gateway.jar
# 启动网关服务
ENTRYPOINT ["java","-jar","supcoder-gateway.jar"]