spring:
  profiles:
    active: db, core, dashboard
  messages:
    encoding: UTF-8
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

server:
  port: 8080
  compression:
    enabled: true
    min-response-size: 2048
    mime-types: application/javascript,text/css,application/json,application/xml,text/html,text/xml,text/plain

logging:
  config: classpath:logback-spring.xml
  level:
    root: DEBUG
    org.springframework: DEBUG
    org.mybatis: DEBUG
    org.apache.catalina: DEBUG
    com.supcoder.hub.dashboard: DEBUG
    com.supcoder.hub.db: DEBUG
    com.supcoder.hub.core: DEBUG
    com.supcoder.hub: DEBUG

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html