# 基础镜像
FROM  openjdk:8-jre
# author
MAINTAINER supcoder

# 挂载目录
VOLUME /home/supcoder
# 创建目录
RUN mkdir -p /home/supcoder
# 指定路径
WORKDIR /home/supcoder
# 复制jar文件到路径
COPY ./jar/supcoder-modules-system.jar /home/supcoder/supcoder-modules-system.jar
# 启动系统服务
ENTRYPOINT ["java","-jar","supcoder-modules-system.jar"]