//package com.supcoder.system.domain;
//
//import java.time.LocalDateTime;
//import java.util.ArrayList;
//import java.util.List;
//
//public class ApiCallLogsExample {
//    /**
//     * This field was generated by MyBatis Generator.
//     * This field corresponds to the database table api_call_logs
//     *
//     * @mbg.generated
//     */
//    protected String orderByClause;
//
//    /**
//     * This field was generated by MyBatis Generator.
//     * This field corresponds to the database table api_call_logs
//     *
//     * @mbg.generated
//     */
//    protected boolean distinct;
//
//    /**
//     * This field was generated by MyBatis Generator.
//     * This field corresponds to the database table api_call_logs
//     *
//     * @mbg.generated
//     */
//    protected List<Criteria> oredCriteria;
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table api_call_logs
//     *
//     * @mbg.generated
//     */
//    public ApiCallLogsExample() {
//        oredCriteria = new ArrayList<Criteria>();
//    }
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table api_call_logs
//     *
//     * @mbg.generated
//     */
//    public void setOrderByClause(String orderByClause) {
//        this.orderByClause = orderByClause;
//    }
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table api_call_logs
//     *
//     * @mbg.generated
//     */
//    public String getOrderByClause() {
//        return orderByClause;
//    }
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table api_call_logs
//     *
//     * @mbg.generated
//     */
//    public void setDistinct(boolean distinct) {
//        this.distinct = distinct;
//    }
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table api_call_logs
//     *
//     * @mbg.generated
//     */
//    public boolean isDistinct() {
//        return distinct;
//    }
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table api_call_logs
//     *
//     * @mbg.generated
//     */
//    public List<Criteria> getOredCriteria() {
//        return oredCriteria;
//    }
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table api_call_logs
//     *
//     * @mbg.generated
//     */
//    public void or(Criteria criteria) {
//        oredCriteria.add(criteria);
//    }
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table api_call_logs
//     *
//     * @mbg.generated
//     */
//    public Criteria or() {
//        Criteria criteria = createCriteriaInternal();
//        oredCriteria.add(criteria);
//        return criteria;
//    }
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table api_call_logs
//     *
//     * @mbg.generated
//     */
//    public ApiCallLogsExample orderBy(String orderByClause) {
//        this.setOrderByClause(orderByClause);
//        return this;
//    }
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table api_call_logs
//     *
//     * @mbg.generated
//     */
//    public ApiCallLogsExample orderBy(String ... orderByClauses) {
//        StringBuffer sb = new StringBuffer();
//        for (int i = 0; i < orderByClauses.length; i++) {
//            sb.append(orderByClauses[i]);
//            if (i < orderByClauses.length - 1) {
//                sb.append(" , ");
//            }
//        }
//        this.setOrderByClause(sb.toString());
//        return this;
//    }
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table api_call_logs
//     *
//     * @mbg.generated
//     */
//    public Criteria createCriteria() {
//        Criteria criteria = createCriteriaInternal();
//        if (oredCriteria.size() == 0) {
//            oredCriteria.add(criteria);
//        }
//        return criteria;
//    }
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table api_call_logs
//     *
//     * @mbg.generated
//     */
//    protected Criteria createCriteriaInternal() {
//        Criteria criteria = new Criteria(this);
//        return criteria;
//    }
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table api_call_logs
//     *
//     * @mbg.generated
//     */
//    public void clear() {
//        oredCriteria.clear();
//        orderByClause = null;
//        distinct = false;
//    }
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table api_call_logs
//     *
//     * @mbg.generated
//     */
//    public static Criteria newAndCreateCriteria() {
//        ApiCallLogsExample example = new ApiCallLogsExample();
//        return example.createCriteria();
//    }
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table api_call_logs
//     *
//     * @mbg.generated
//     */
//    public ApiCallLogsExample when(boolean condition, IExampleWhen then) {
//        if (condition) {
//            then.example(this);
//        }
//        return this;
//    }
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table api_call_logs
//     *
//     * @mbg.generated
//     */
//    public ApiCallLogsExample when(boolean condition, IExampleWhen then, IExampleWhen otherwise) {
//        if (condition) {
//            then.example(this);
//        } else {
//            otherwise.example(this);
//        }
//        return this;
//    }
//
//    /**
//     * This class was generated by MyBatis Generator.
//     * This class corresponds to the database table api_call_logs
//     *
//     * @mbg.generated
//     */
//    protected abstract static class GeneratedCriteria {
//        protected List<Criterion> criteria;
//
//        protected GeneratedCriteria() {
//            super();
//            criteria = new ArrayList<Criterion>();
//        }
//
//        public boolean isValid() {
//            return criteria.size() > 0;
//        }
//
//        public List<Criterion> getAllCriteria() {
//            return criteria;
//        }
//
//        public List<Criterion> getCriteria() {
//            return criteria;
//        }
//
//        protected void addCriterion(String condition) {
//            if (condition == null) {
//                throw new RuntimeException("Value for condition cannot be null");
//            }
//            criteria.add(new Criterion(condition));
//        }
//
//        protected void addCriterion(String condition, Object value, String property) {
//            if (value == null) {
//                throw new RuntimeException("Value for " + property + " cannot be null");
//            }
//            criteria.add(new Criterion(condition, value));
//        }
//
//        protected void addCriterion(String condition, Object value1, Object value2, String property) {
//            if (value1 == null || value2 == null) {
//                throw new RuntimeException("Between values for " + property + " cannot be null");
//            }
//            criteria.add(new Criterion(condition, value1, value2));
//        }
//
//        public Criteria andLogIdIsNull() {
//            addCriterion("log_id is null");
//            return (Criteria) this;
//        }
//
//        public Criteria andLogIdIsNotNull() {
//            addCriterion("log_id is not null");
//            return (Criteria) this;
//        }
//
//        public Criteria andLogIdEqualTo(Integer value) {
//            addCriterion("log_id =", value, "logId");
//            return (Criteria) this;
//        }
//
//        /**
//         * This method was generated by MyBatis Generator.
//         * This method corresponds to the database table api_call_logs
//         *
//         * @mbg.generated
//         */
//        public Criteria andLogIdEqualToColumn(ApiCallLogs.Column column) {
//            addCriterion(new StringBuilder("log_id = ").append(column.getEscapedColumnName()).toString());
//            return (Criteria) this;
//        }
//
//        public Criteria andLogIdNotEqualTo(Integer value) {
//            addCriterion("log_id <>", value, "logId");
//            return (Criteria) this;
//        }
//
//        /**
//         * This method was generated by MyBatis Generator.
//         * This method corresponds to the database table api_call_logs
//         *
//         * @mbg.generated
//         */
//        public Criteria andLogIdNotEqualToColumn(ApiCallLogs.Column column) {
//            addCriterion(new StringBuilder("log_id <> ").append(column.getEscapedColumnName()).toString());
//            return (Criteria) this;
//        }
//
//        public Criteria andLogIdGreaterThan(Integer value) {
//            addCriterion("log_id >", value, "logId");
//            return (Criteria) this;
//        }
//
//        /**
//         * This method was generated by MyBatis Generator.
//         * This method corresponds to the database table api_call_logs
//         *
//         * @mbg.generated
//         */
//        public Criteria andLogIdGreaterThanColumn(ApiCallLogs.Column column) {
//            addCriterion(new StringBuilder("log_id > ").append(column.getEscapedColumnName()).toString());
//            return (Criteria) this;
//        }
//
//        public Criteria andLogIdGreaterThanOrEqualTo(Integer value) {
//            addCriterion("log_id >=", value, "logId");
//            return (Criteria) this;
//        }
//
//        /**
//         * This method was generated by MyBatis Generator.
//         * This method corresponds to the database table api_call_logs
//         *
//         * @mbg.generated
//         */
//        public Criteria andLogIdGreaterThanOrEqualToColumn(ApiCallLogs.Column column) {
//            addCriterion(new StringBuilder("log_id >= ").append(column.getEscapedColumnName()).toString());
//            return (Criteria) this;
//        }
//
//        public Criteria andLogIdLessThan(Integer value) {
//            addCriterion("log_id <", value, "logId");
//            return (Criteria) this;
//        }
//
//        /**
//         * This method was generated by MyBatis Generator.
//         * This method corresponds to the database table api_call_logs
//         *
//         * @mbg.generated
//         */
//        public Criteria andLogIdLessThanColumn(ApiCallLogs.Column column) {
//            addCriterion(new StringBuilder("log_id < ").append(column.getEscapedColumnName()).toString());
//            return (Criteria) this;
//        }
//
//        public Criteria andLogIdLessThanOrEqualTo(Integer value) {
//            addCriterion("log_id <=", value, "logId");
//            return (Criteria) this;
//        }
//
//        /**
//         * This method was generated by MyBatis Generator.
//         * This method corresponds to the database table api_call_logs
//         *
//         * @mbg.generated
//         */
//        public Criteria andLogIdLessThanOrEqualToColumn(ApiCallLogs.Column column) {
//            addCriterion(new StringBuilder("log_id <= ").append(column.getEscapedColumnName()).toString());
//            return (Criteria) this;
//        }
//
//        public Criteria andLogIdIn(List<Integer> values) {
//            addCriterion("log_id in", values, "logId");
//            return (Criteria) this;
//        }
//
//        public Criteria andLogIdNotIn(List<Integer> values) {
//            addCriterion("log_id not in", values, "logId");
//            return (Criteria) this;
//        }
//
//        public Criteria andLogIdBetween(Integer value1, Integer value2) {
//            addCriterion("log_id between", value1, value2, "logId");
//            return (Criteria) this;
//        }
//
//        public Criteria andLogIdNotBetween(Integer value1, Integer value2) {
//            addCriterion("log_id not between", value1, value2, "logId");
//            return (Criteria) this;
//        }
//
//        public Criteria andKeyIdIsNull() {
//            addCriterion("key_id is null");
//            return (Criteria) this;
//        }
//
//        public Criteria andKeyIdIsNotNull() {
//            addCriterion("key_id is not null");
//            return (Criteria) this;
//        }
//
//        public Criteria andKeyIdEqualTo(Integer value) {
//            addCriterion("key_id =", value, "keyId");
//            return (Criteria) this;
//        }
//
//        /**
//         * This method was generated by MyBatis Generator.
//         * This method corresponds to the database table api_call_logs
//         *
//         * @mbg.generated
//         */
//        public Criteria andKeyIdEqualToColumn(ApiCallLogs.Column column) {
//            addCriterion(new StringBuilder("key_id = ").append(column.getEscapedColumnName()).toString());
//            return (Criteria) this;
//        }
//
//        public Criteria andKeyIdNotEqualTo(Integer value) {
//            addCriterion("key_id <>", value, "keyId");
//            return (Criteria) this;
//        }
//
//        /**
//         * This method was generated by MyBatis Generator.
//         * This method corresponds to the database table api_call_logs
//         *
//         * @mbg.generated
//         */
//        public Criteria andKeyIdNotEqualToColumn(ApiCallLogs.Column column) {
//            addCriterion(new StringBuilder("key_id <> ").append(column.getEscapedColumnName()).toString());
//            return (Criteria) this;
//        }
//
//        public Criteria andKeyIdGreaterThan(Integer value) {
//            addCriterion("key_id >", value, "keyId");
//            return (Criteria) this;
//        }
//
//        /**
//         * This method was generated by MyBatis Generator.
//         * This method corresponds to the database table api_call_logs
//         *
//         * @mbg.generated
//         */
//        public Criteria andKeyIdGreaterThanColumn(ApiCallLogs.Column column) {
//            addCriterion(new StringBuilder("key_id > ").append(column.getEscapedColumnName()).toString());
//            return (Criteria) this;
//        }
//
//        public Criteria andKeyIdGreaterThanOrEqualTo(Integer value) {
//            addCriterion("key_id >=", value, "keyId");
//            return (Criteria) this;
//        }
//
//        /**
//         * This method was generated by MyBatis Generator.
//         * This method corresponds to the database table api_call_logs
//         *
//         * @mbg.generated
//         */
//        public Criteria andKeyIdGreaterThanOrEqualToColumn(ApiCallLogs.Column column) {
//            addCriterion(new StringBuilder("key_id >= ").append(column.getEscapedColumnName()).toString());
//            return (Criteria) this;
//        }
//
//        public Criteria andKeyIdLessThan(Integer value) {
//            addCriterion("key_id <", value, "keyId");
//            return (Criteria) this;
//        }
//
//        /**
//         * This method was generated by MyBatis Generator.
//         * This method corresponds to the database table api_call_logs
//         *
//         * @mbg.generated
//         */
//        public Criteria andKeyIdLessThanColumn(ApiCallLogs.Column column) {
//            addCriterion(new StringBuilder("key_id < ").append(column.getEscapedColumnName()).toString());
//            return (Criteria) this;
//        }
//
//        public Criteria andKeyIdLessThanOrEqualTo(Integer value) {
//            addCriterion("key_id <=", value, "keyId");
//            return (Criteria) this;
//        }
//
//        /**
//         * This method was generated by MyBatis Generator.
//         * This method corresponds to the database table api_call_logs
//         *
//         * @mbg.generated
//         */
//        public Criteria andKeyIdLessThanOrEqualToColumn(ApiCallLogs.Column column) {
//            addCriterion(new StringBuilder("key_id <= ").append(column.getEscapedColumnName()).toString());
//            return (Criteria) this;
//        }
//
//        public Criteria andKeyIdIn(List<Integer> values) {
//            addCriterion("key_id in", values, "keyId");
//            return (Criteria) this;
//        }
//
//        public Criteria andKeyIdNotIn(List<Integer> values) {
//            addCriterion("key_id not in", values, "keyId");
//            return (Criteria) this;
//        }
//
//        public Criteria andKeyIdBetween(Integer value1, Integer value2) {
//            addCriterion("key_id between", value1, value2, "keyId");
//            return (Criteria) this;
//        }
//
//        public Criteria andKeyIdNotBetween(Integer value1, Integer value2) {
//            addCriterion("key_id not between", value1, value2, "keyId");
//            return (Criteria) this;
//        }
//
//        public Criteria andUsernameIsNull() {
//            addCriterion("username is null");
//            return (Criteria) this;
//        }
//
//        public Criteria andUsernameIsNotNull() {
//            addCriterion("username is not null");
//            return (Criteria) this;
//        }
//
//        public Criteria andUsernameEqualTo(String value) {
//            addCriterion("username =", value, "username");
//            return (Criteria) this;
//        }
//
//        /**
//         * This method was generated by MyBatis Generator.
//         * This method corresponds to the database table api_call_logs
//         *
//         * @mbg.generated
//         */
//        public Criteria andUsernameEqualToColumn(ApiCallLogs.Column column) {
//            addCriterion(new StringBuilder("username = ").append(column.getEscapedColumnName()).toString());
//            return (Criteria) this;
//        }
//
//        public Criteria andUsernameNotEqualTo(String value) {
//            addCriterion("username <>", value, "username");
//            return (Criteria) this;
//        }
//
//        /**
//         * This method was generated by MyBatis Generator.
//         * This method corresponds to the database table api_call_logs
//         *
//         * @mbg.generated
//         */
//        public Criteria andUsernameNotEqualToColumn(ApiCallLogs.Column column) {
//            addCriterion(new StringBuilder("username <> ").append(column.getEscapedColumnName()).toString());
//            return (Criteria) this;
//        }
//
//        public Criteria andUsernameGreaterThan(String value) {
//            addCriterion("username >", value, "username");
//            return (Criteria) this;
//        }
//
//        /**
//         * This method was generated by MyBatis Generator.
//         * This method corresponds to the database table api_call_logs
//         *
//         * @mbg.generated
//         */
//        public Criteria andUsernameGreaterThanColumn(ApiCallLogs.Column column) {
//            addCriterion(new StringBuilder("username > ").append(column.getEscapedColumnName()).toString());
//            return (Criteria) this;
//        }
//
//        public Criteria andUsernameGreaterThanOrEqualTo(String value) {
//            addCriterion("username >=", value, "username");
//            return (Criteria) this;
//        }
//
//        /**
//         * This method was generated by MyBatis Generator.
//         * This method corresponds to the database table api_call_logs
//         *
//         * @mbg.generated
//         */
//        public Criteria andUsernameGreaterThanOrEqualToColumn(ApiCallLogs.Column column) {
//            addCriterion(new StringBuilder("username >= ").append(column.getEscapedColumnName()).toString());
//            return (Criteria) this;
//        }
//
//        public Criteria andUsernameLessThan(String value) {
//            addCriterion("username <", value, "username");
//            return (Criteria) this;
//        }
//
//        /**
//         * This method was generated by MyBatis Generator.
//         * This method corresponds to the database table api_call_logs
//         *
//         * @mbg.generated
//         */
//        public Criteria andUsernameLessThanColumn(ApiCallLogs.Column column) {
//            addCriterion(new StringBuilder("username < ").append(column.getEscapedColumnName()).toString());
//            return (Criteria) this;
//        }
//
//        public Criteria andUsernameLessThanOrEqualTo(String value) {
//            addCriterion("username <=", value, "username");
//            return (Criteria) this;
//        }
//
//        /**
//         * This method was generated by MyBatis Generator.
//         * This method corresponds to the database table api_call_logs
//         *
//         * @mbg.generated
//         */
//        public Criteria andUsernameLessThanOrEqualToColumn(ApiCallLogs.Column column) {
//            addCriterion(new StringBuilder("username <= ").append(column.getEscapedColumnName()).toString());
//            return (Criteria) this;
//        }
//
//        public Criteria andUsernameLike(String value) {
//            addCriterion("username like", value, "username");
//            return (Criteria) this;
//        }
//
//        public Criteria andUsernameNotLike(String value) {
//            addCriterion("username not like", value, "username");
//            return (Criteria) this;
//        }
//
//        public Criteria andUsernameIn(List<String> values) {
//            addCriterion("username in", values, "username");
//            return (Criteria) this;
//        }
//
//        public Criteria andUsernameNotIn(List<String> values) {
//            addCriterion("username not in", values, "username");
//            return (Criteria) this;
//        }
//
//        public Criteria andUsernameBetween(String value1, String value2) {
//            addCriterion("username between", value1, value2, "username");
//            return (Criteria) this;
//        }
//
//        public Criteria andUsernameNotBetween(String value1, String value2) {
//            addCriterion("username not between", value1, value2, "username");
//            return (Criteria) this;
//        }
//
//        public Criteria andServiceIsNull() {
//            addCriterion("service is null");
//            return (Criteria) this;
//        }
//
//        public Criteria andServiceIsNotNull() {
//            addCriterion("service is not null");
//            return (Criteria) this;
//        }
//
//        public Criteria andServiceEqualTo(String value) {
//            addCriterion("service =", value, "service");
//            return (Criteria) this;
//        }
//
//        /**
//         * This method was generated by MyBatis Generator.
//         * This method corresponds to the database table api_call_logs
//         *
//         * @mbg.generated
//         */
//        public Criteria andServiceEqualToColumn(ApiCallLogs.Column column) {
//            addCriterion(new StringBuilder("service = ").append(column.getEscapedColumnName()).toString());
//            return (Criteria) this;
//        }
//
//        public Criteria andServiceNotEqualTo(String value) {
//            addCriterion("service <>", value, "service");
//            return (Criteria) this;
//        }
//
//        /**
//         * This method was generated by MyBatis Generator.
//         * This method corresponds to the database table api_call_logs
//         *
//         * @mbg.generated
//         */
//        public Criteria andServiceNotEqualToColumn(ApiCallLogs.Column column) {
//            addCriterion(new StringBuilder("service <> ").append(column.getEscapedColumnName()).toString());
//            return (Criteria) this;
//        }
//
//        public Criteria andServiceGreaterThan(String value) {
//            addCriterion("service >", value, "service");
//            return (Criteria) this;
//        }
//
//        /**
//         * This method was generated by MyBatis Generator.
//         * This method corresponds to the database table api_call_logs
//         *
//         * @mbg.generated
//         */
//        public Criteria andServiceGreaterThanColumn(ApiCallLogs.Column column) {
//            addCriterion(new StringBuilder("service > ").append(column.getEscapedColumnName()).toString());
//            return (Criteria) this;
//        }
//
//        public Criteria andServiceGreaterThanOrEqualTo(String value) {
//            addCriterion("service >=", value, "service");
//            return (Criteria) this;
//        }
//
//        /**
//         * This method was generated by MyBatis Generator.
//         * This method corresponds to the database table api_call_logs
//         *
//         * @mbg.generated
//         */
//        public Criteria andServiceGreaterThanOrEqualToColumn(ApiCallLogs.Column column) {
//            addCriterion(new StringBuilder("service >= ").append(column.getEscapedColumnName()).toString());
//            return (Criteria) this;
//        }
//
//        public Criteria andServiceLessThan(String value) {
//            addCriterion("service <", value, "service");
//            return (Criteria) this;
//        }
//
//        /**
//         * This method was generated by MyBatis Generator.
//         * This method corresponds to the database table api_call_logs
//         *
//         * @mbg.generated
//         */
//        public Criteria andServiceLessThanColumn(ApiCallLogs.Column column) {
//            addCriterion(new StringBuilder("service < ").append(column.getEscapedColumnName()).toString());
//            return (Criteria) this;
//        }
//
//        public Criteria andServiceLessThanOrEqualTo(String value) {
//            addCriterion("service <=", value, "service");
//            return (Criteria) this;
//        }
//
//        /**
//         * This method was generated by MyBatis Generator.
//         * This method corresponds to the database table api_call_logs
//         *
//         * @mbg.generated
//         */
//        public Criteria andServiceLessThanOrEqualToColumn(ApiCallLogs.Column column) {
//            addCriterion(new StringBuilder("service <= ").append(column.getEscapedColumnName()).toString());
//            return (Criteria) this;
//        }
//
//        public Criteria andServiceLike(String value) {
//            addCriterion("service like", value, "service");
//            return (Criteria) this;
//        }
//
//        public Criteria andServiceNotLike(String value) {
//            addCriterion("service not like", value, "service");
//            return (Criteria) this;
//        }
//
//        public Criteria andServiceIn(List<String> values) {
//            addCriterion("service in", values, "service");
//            return (Criteria) this;
//        }
//
//        public Criteria andServiceNotIn(List<String> values) {
//            addCriterion("service not in", values, "service");
//            return (Criteria) this;
//        }
//
//        public Criteria andServiceBetween(String value1, String value2) {
//            addCriterion("service between", value1, value2, "service");
//            return (Criteria) this;
//        }
//
//        public Criteria andServiceNotBetween(String value1, String value2) {
//            addCriterion("service not between", value1, value2, "service");
//            return (Criteria) this;
//        }
//
//        public Criteria andRequestMethodIsNull() {
//            addCriterion("request_method is null");
//            return (Criteria) this;
//        }
//
//        public Criteria andRequestMethodIsNotNull() {
//            addCriterion("request_method is not null");
//            return (Criteria) this;
//        }
//
//        public Criteria andRequestMethodEqualTo(String value) {
//            addCriterion("request_method =", value, "requestMethod");
//            return (Criteria) this;
//        }
//
//        /**
//         * This method was generated by MyBatis Generator.
//         * This method corresponds to the database table api_call_logs
//         *
//         * @mbg.generated
//         */
//        public Criteria andRequestMethodEqualToColumn(ApiCallLogs.Column column) {
//            addCriterion(new StringBuilder("request_method = ").append(column.getEscapedColumnName()).toString());
//            return (Criteria) this;
//        }
//
//        public Criteria andRequestMethodNotEqualTo(String value) {
//            addCriterion("request_method <>", value, "requestMethod");
//            return (Criteria) this;
//        }
//
//        /**
//         * This method was generated by MyBatis Generator.
//         * This method corresponds to the database table api_call_logs
//         *
//         * @mbg.generated
//         */
//        public Criteria andRequestMethodNotEqualToColumn(ApiCallLogs.Column column) {
//            addCriterion(new StringBuilder("request_method <> ").append(column.getEscapedColumnName()).toString());
//            return (Criteria) this;
//        }
//
//        public Criteria andRequestMethodGreaterThan(String value) {
//            addCriterion("request_method >", value, "requestMethod");
//            return (Criteria) this;
//        }
//
//        /**
//         * This method was generated by MyBatis Generator.
//         * This method corresponds to the database table api_call_logs
//         *
//         * @mbg.generated
//         */
//        public Criteria andRequestMethodGreaterThanColumn(ApiCallLogs.Column column) {
//            addCriterion(new StringBuilder("request_method > ").append(column.getEscapedColumnName()).toString());
//            return (Criteria) this;
//        }
//
//        public Criteria andRequestMethodGreaterThanOrEqualTo(String value) {
//            addCriterion("request_method >=", value, "requestMethod");
//            return (Criteria) this;
//        }
//
//        /**
//         * This method was generated by MyBatis Generator.
//         * This method corresponds to the database table api_call_logs
//         *
//         * @mbg.generated
//         */
//        public Criteria andRequestMethodGreaterThanOrEqualToColumn(ApiCallLogs.Column column) {
//            addCriterion(new StringBuilder("request_method >= ").append(column.getEscapedColumnName()).toString());
//            return (Criteria) this;
//        }
//
//        public Criteria andRequestMethodLessThan(String value) {
//            addCriterion("request_method <", value, "requestMethod");
//            return (Criteria) this;
//        }
//
//        /**
//         * This method was generated by MyBatis Generator.
//         * This method corresponds to the database table api_call_logs
//         *
//         * @mbg.generated
//         */
//        public Criteria andRequestMethodLessThanColumn(ApiCallLogs.Column column) {
//            addCriterion(new StringBuilder("request_method < ").append(column.getEscapedColumnName()).toString());
//            return (Criteria) this;
//        }
//
//        public Criteria andRequestMethodLessThanOrEqualTo(String value) {
//            addCriterion("request_method <=", value, "requestMethod");
//            return (Criteria) this;
//        }
//
//        /**
//         * This method was generated by MyBatis Generator.
//         * This method corresponds to the database table api_call_logs
//         *
//         * @mbg.generated
//         */
//        public Criteria andRequestMethodLessThanOrEqualToColumn(ApiCallLogs.Column column) {
//            addCriterion(new StringBuilder("request_method <= ").append(column.getEscapedColumnName()).toString());
//            return (Criteria) this;
//        }
//
//        public Criteria andRequestMethodLike(String value) {
//            addCriterion("request_method like", value, "requestMethod");
//            return (Criteria) this;
//        }
//
//        public Criteria andRequestMethodNotLike(String value) {
//            addCriterion("request_method not like", value, "requestMethod");
//            return (Criteria) this;
//        }
//
//        public Criteria andRequestMethodIn(List<String> values) {
//            addCriterion("request_method in", values, "requestMethod");
//            return (Criteria) this;
//        }
//
//        public Criteria andRequestMethodNotIn(List<String> values) {
//            addCriterion("request_method not in", values, "requestMethod");
//            return (Criteria) this;
//        }
//
//        public Criteria andRequestMethodBetween(String value1, String value2) {
//            addCriterion("request_method between", value1, value2, "requestMethod");
//            return (Criteria) this;
//        }
//
//        public Criteria andRequestMethodNotBetween(String value1, String value2) {
//            addCriterion("request_method not between", value1, value2, "requestMethod");
//            return (Criteria) this;
//        }
//
//        public Criteria andRequestUrlIsNull() {
//            addCriterion("request_url is null");
//            return (Criteria) this;
//        }
//
//        public Criteria andRequestUrlIsNotNull() {
//            addCriterion("request_url is not null");
//            return (Criteria) this;
//        }
//
//        public Criteria andRequestUrlEqualTo(String value) {
//            addCriterion("request_url =", value, "requestUrl");
//            return (Criteria) this;
//        }
//
//        /**
//         * This method was generated by MyBatis Generator.
//         * This method corresponds to the database table api_call_logs
//         *
//         * @mbg.generated
//         */
//        public Criteria andRequestUrlEqualToColumn(ApiCallLogs.Column column) {
//            addCriterion(new StringBuilder("request_url = ").append(column.getEscapedColumnName()).toString());
//            return (Criteria) this;
//        }
//
//        public Criteria andRequestUrlNotEqualTo(String value) {
//            addCriterion("request_url <>", value, "requestUrl");
//            return (Criteria) this;
//        }
//
//        /**
//         * This method was generated by MyBatis Generator.
//         * This method corresponds to the database table api_call_logs
//         *
//         * @mbg.generated
//         */
//        public Criteria andRequestUrlNotEqualToColumn(ApiCallLogs.Column column) {
//            addCriterion(new StringBuilder("request_url <> ").append(column.getEscapedColumnName()).toString());
//            return (Criteria) this;
//        }
//
//        public Criteria andRequestUrlGreaterThan(String value) {
//            addCriterion("request_url >", value, "requestUrl");
//            return (Criteria) this;
//        }
//
//        /**
//         * This method was generated by MyBatis Generator.
//         * This method corresponds to the database table api_call_logs
//         *
//         * @mbg.generated
//         */
//        public Criteria andRequestUrlGreaterThanColumn(ApiCallLogs.Column column) {
//            addCriterion(new StringBuilder("request_url > ").append(column.getEscapedColumnName()).toString());
//            return (Criteria) this;
//        }
//
//        public Criteria andRequestUrlGreaterThanOrEqualTo(String value) {
//            addCriterion("request_url >=", value, "requestUrl");
//            return (Criteria) this;
//        }
//
//        /**
//         * This method was generated by MyBatis Generator.
//         * This method corresponds to the database table api_call_logs
//         *
//         * @mbg.generated
//         */
//        public Criteria andRequestUrlGreaterThanOrEqualToColumn(ApiCallLogs.Column column) {
//            addCriterion(new StringBuilder("request_url >= ").append(column.getEscapedColumnName()).toString());
//            return (Criteria) this;
//        }
//
//        public Criteria andRequestUrlLessThan(String value) {
//            addCriterion("request_url <", value, "requestUrl");
//            return (Criteria) this;
//        }
//
//        /**
//         * This method was generated by MyBatis Generator.
//         * This method corresponds to the database table api_call_logs
//         *
//         * @mbg.generated
//         */
//        public Criteria andRequestUrlLessThanColumn(ApiCallLogs.Column column) {
//            addCriterion(new StringBuilder("request_url < ").append(column.getEscapedColumnName()).toString());
//            return (Criteria) this;
//        }
//
//        public Criteria andRequestUrlLessThanOrEqualTo(String value) {
//            addCriterion("request_url <=", value, "requestUrl");
//            return (Criteria) this;
//        }
//
//        /**
//         * This method was generated by MyBatis Generator.
//         * This method corresponds to the database table api_call_logs
//         *
//         * @mbg.generated
//         */
//        public Criteria andRequestUrlLessThanOrEqualToColumn(ApiCallLogs.Column column) {
//            addCriterion(new StringBuilder("request_url <= ").append(column.getEscapedColumnName()).toString());
//            return (Criteria) this;
//        }
//
//        public Criteria andRequestUrlLike(String value) {
//            addCriterion("request_url like", value, "requestUrl");
//            return (Criteria) this;
//        }
//
//        public Criteria andRequestUrlNotLike(String value) {
//            addCriterion("request_url not like", value, "requestUrl");
//            return (Criteria) this;
//        }
//
//        public Criteria andRequestUrlIn(List<String> values) {
//            addCriterion("request_url in", values, "requestUrl");
//            return (Criteria) this;
//        }
//
//        public Criteria andRequestUrlNotIn(List<String> values) {
//            addCriterion("request_url not in", values, "requestUrl");
//            return (Criteria) this;
//        }
//
//        public Criteria andRequestUrlBetween(String value1, String value2) {
//            addCriterion("request_url between", value1, value2, "requestUrl");
//            return (Criteria) this;
//        }
//
//        public Criteria andRequestUrlNotBetween(String value1, String value2) {
//            addCriterion("request_url not between", value1, value2, "requestUrl");
//            return (Criteria) this;
//        }
//
//        public Criteria andRequestDateIsNull() {
//            addCriterion("request_date is null");
//            return (Criteria) this;
//        }
//
//        public Criteria andRequestDateIsNotNull() {
//            addCriterion("request_date is not null");
//            return (Criteria) this;
//        }
//
//        public Criteria andRequestDateEqualTo(LocalDateTime value) {
//            addCriterion("request_date =", value, "requestDate");
//            return (Criteria) this;
//        }
//
//        /**
//         * This method was generated by MyBatis Generator.
//         * This method corresponds to the database table api_call_logs
//         *
//         * @mbg.generated
//         */
//        public Criteria andRequestDateEqualToColumn(ApiCallLogs.Column column) {
//            addCriterion(new StringBuilder("request_date = ").append(column.getEscapedColumnName()).toString());
//            return (Criteria) this;
//        }
//
//        public Criteria andRequestDateNotEqualTo(LocalDateTime value) {
//            addCriterion("request_date <>", value, "requestDate");
//            return (Criteria) this;
//        }
//
//        /**
//         * This method was generated by MyBatis Generator.
//         * This method corresponds to the database table api_call_logs
//         *
//         * @mbg.generated
//         */
//        public Criteria andRequestDateNotEqualToColumn(ApiCallLogs.Column column) {
//            addCriterion(new StringBuilder("request_date <> ").append(column.getEscapedColumnName()).toString());
//            return (Criteria) this;
//        }
//
//        public Criteria andRequestDateGreaterThan(LocalDateTime value) {
//            addCriterion("request_date >", value, "requestDate");
//            return (Criteria) this;
//        }
//
//        /**
//         * This method was generated by MyBatis Generator.
//         * This method corresponds to the database table api_call_logs
//         *
//         * @mbg.generated
//         */
//        public Criteria andRequestDateGreaterThanColumn(ApiCallLogs.Column column) {
//            addCriterion(new StringBuilder("request_date > ").append(column.getEscapedColumnName()).toString());
//            return (Criteria) this;
//        }
//
//        public Criteria andRequestDateGreaterThanOrEqualTo(LocalDateTime value) {
//            addCriterion("request_date >=", value, "requestDate");
//            return (Criteria) this;
//        }
//
//        /**
//         * This method was generated by MyBatis Generator.
//         * This method corresponds to the database table api_call_logs
//         *
//         * @mbg.generated
//         */
//        public Criteria andRequestDateGreaterThanOrEqualToColumn(ApiCallLogs.Column column) {
//            addCriterion(new StringBuilder("request_date >= ").append(column.getEscapedColumnName()).toString());
//            return (Criteria) this;
//        }
//
//        public Criteria andRequestDateLessThan(LocalDateTime value) {
//            addCriterion("request_date <", value, "requestDate");
//            return (Criteria) this;
//        }
//
//        /**
//         * This method was generated by MyBatis Generator.
//         * This method corresponds to the database table api_call_logs
//         *
//         * @mbg.generated
//         */
//        public Criteria andRequestDateLessThanColumn(ApiCallLogs.Column column) {
//            addCriterion(new StringBuilder("request_date < ").append(column.getEscapedColumnName()).toString());
//            return (Criteria) this;
//        }
//
//        public Criteria andRequestDateLessThanOrEqualTo(LocalDateTime value) {
//            addCriterion("request_date <=", value, "requestDate");
//            return (Criteria) this;
//        }
//
//        /**
//         * This method was generated by MyBatis Generator.
//         * This method corresponds to the database table api_call_logs
//         *
//         * @mbg.generated
//         */
//        public Criteria andRequestDateLessThanOrEqualToColumn(ApiCallLogs.Column column) {
//            addCriterion(new StringBuilder("request_date <= ").append(column.getEscapedColumnName()).toString());
//            return (Criteria) this;
//        }
//
//        public Criteria andRequestDateIn(List<LocalDateTime> values) {
//            addCriterion("request_date in", values, "requestDate");
//            return (Criteria) this;
//        }
//
//        public Criteria andRequestDateNotIn(List<LocalDateTime> values) {
//            addCriterion("request_date not in", values, "requestDate");
//            return (Criteria) this;
//        }
//
//        public Criteria andRequestDateBetween(LocalDateTime value1, LocalDateTime value2) {
//            addCriterion("request_date between", value1, value2, "requestDate");
//            return (Criteria) this;
//        }
//
//        public Criteria andRequestDateNotBetween(LocalDateTime value1, LocalDateTime value2) {
//            addCriterion("request_date not between", value1, value2, "requestDate");
//            return (Criteria) this;
//        }
//
//        public Criteria andResponseStatusIsNull() {
//            addCriterion("response_status is null");
//            return (Criteria) this;
//        }
//
//        public Criteria andResponseStatusIsNotNull() {
//            addCriterion("response_status is not null");
//            return (Criteria) this;
//        }
//
//        public Criteria andResponseStatusEqualTo(Integer value) {
//            addCriterion("response_status =", value, "responseStatus");
//            return (Criteria) this;
//        }
//
//        /**
//         * This method was generated by MyBatis Generator.
//         * This method corresponds to the database table api_call_logs
//         *
//         * @mbg.generated
//         */
//        public Criteria andResponseStatusEqualToColumn(ApiCallLogs.Column column) {
//            addCriterion(new StringBuilder("response_status = ").append(column.getEscapedColumnName()).toString());
//            return (Criteria) this;
//        }
//
//        public Criteria andResponseStatusNotEqualTo(Integer value) {
//            addCriterion("response_status <>", value, "responseStatus");
//            return (Criteria) this;
//        }
//
//        /**
//         * This method was generated by MyBatis Generator.
//         * This method corresponds to the database table api_call_logs
//         *
//         * @mbg.generated
//         */
//        public Criteria andResponseStatusNotEqualToColumn(ApiCallLogs.Column column) {
//            addCriterion(new StringBuilder("response_status <> ").append(column.getEscapedColumnName()).toString());
//            return (Criteria) this;
//        }
//
//        public Criteria andResponseStatusGreaterThan(Integer value) {
//            addCriterion("response_status >", value, "responseStatus");
//            return (Criteria) this;
//        }
//
//        /**
//         * This method was generated by MyBatis Generator.
//         * This method corresponds to the database table api_call_logs
//         *
//         * @mbg.generated
//         */
//        public Criteria andResponseStatusGreaterThanColumn(ApiCallLogs.Column column) {
//            addCriterion(new StringBuilder("response_status > ").append(column.getEscapedColumnName()).toString());
//            return (Criteria) this;
//        }
//
//        public Criteria andResponseStatusGreaterThanOrEqualTo(Integer value) {
//            addCriterion("response_status >=", value, "responseStatus");
//            return (Criteria) this;
//        }
//
//        /**
//         * This method was generated by MyBatis Generator.
//         * This method corresponds to the database table api_call_logs
//         *
//         * @mbg.generated
//         */
//        public Criteria andResponseStatusGreaterThanOrEqualToColumn(ApiCallLogs.Column column) {
//            addCriterion(new StringBuilder("response_status >= ").append(column.getEscapedColumnName()).toString());
//            return (Criteria) this;
//        }
//
//        public Criteria andResponseStatusLessThan(Integer value) {
//            addCriterion("response_status <", value, "responseStatus");
//            return (Criteria) this;
//        }
//
//        /**
//         * This method was generated by MyBatis Generator.
//         * This method corresponds to the database table api_call_logs
//         *
//         * @mbg.generated
//         */
//        public Criteria andResponseStatusLessThanColumn(ApiCallLogs.Column column) {
//            addCriterion(new StringBuilder("response_status < ").append(column.getEscapedColumnName()).toString());
//            return (Criteria) this;
//        }
//
//        public Criteria andResponseStatusLessThanOrEqualTo(Integer value) {
//            addCriterion("response_status <=", value, "responseStatus");
//            return (Criteria) this;
//        }
//
//        /**
//         * This method was generated by MyBatis Generator.
//         * This method corresponds to the database table api_call_logs
//         *
//         * @mbg.generated
//         */
//        public Criteria andResponseStatusLessThanOrEqualToColumn(ApiCallLogs.Column column) {
//            addCriterion(new StringBuilder("response_status <= ").append(column.getEscapedColumnName()).toString());
//            return (Criteria) this;
//        }
//
//        public Criteria andResponseStatusIn(List<Integer> values) {
//            addCriterion("response_status in", values, "responseStatus");
//            return (Criteria) this;
//        }
//
//        public Criteria andResponseStatusNotIn(List<Integer> values) {
//            addCriterion("response_status not in", values, "responseStatus");
//            return (Criteria) this;
//        }
//
//        public Criteria andResponseStatusBetween(Integer value1, Integer value2) {
//            addCriterion("response_status between", value1, value2, "responseStatus");
//            return (Criteria) this;
//        }
//
//        public Criteria andResponseStatusNotBetween(Integer value1, Integer value2) {
//            addCriterion("response_status not between", value1, value2, "responseStatus");
//            return (Criteria) this;
//        }
//    }
//
//    /**
//     * This class was generated by MyBatis Generator.
//     * This class corresponds to the database table api_call_logs
//     *
//     * @mbg.generated do_not_delete_during_merge
//     */
//    public static class Criteria extends GeneratedCriteria {
//        /**
//         * This field was generated by MyBatis Generator.
//         * This field corresponds to the database table api_call_logs
//         *
//         * @mbg.generated
//         */
//        private ApiCallLogsExample example;
//
//        /**
//         * This method was generated by MyBatis Generator.
//         * This method corresponds to the database table api_call_logs
//         *
//         * @mbg.generated
//         */
//        protected Criteria(ApiCallLogsExample example) {
//            super();
//            this.example = example;
//        }
//
//        /**
//         * This method was generated by MyBatis Generator.
//         * This method corresponds to the database table api_call_logs
//         *
//         * @mbg.generated
//         */
//        public ApiCallLogsExample example() {
//            return this.example;
//        }
//
//        /**
//         * This method was generated by MyBatis Generator.
//         * This method corresponds to the database table api_call_logs
//         *
//         * @mbg.generated
//         */
//        @Deprecated
//        public Criteria andIf(boolean ifAdd, ICriteriaAdd add) {
//            if (ifAdd) {
//                add.add(this);
//            }
//            return this;
//        }
//
//        /**
//         * This method was generated by MyBatis Generator.
//         * This method corresponds to the database table api_call_logs
//         *
//         * @mbg.generated
//         */
//        public Criteria when(boolean condition, ICriteriaWhen then) {
//            if (condition) {
//                then.criteria(this);
//            }
//            return this;
//        }
//
//        /**
//         * This method was generated by MyBatis Generator.
//         * This method corresponds to the database table api_call_logs
//         *
//         * @mbg.generated
//         */
//        public Criteria when(boolean condition, ICriteriaWhen then, ICriteriaWhen otherwise) {
//            if (condition) {
//                then.criteria(this);
//            } else {
//                otherwise.criteria(this);
//            }
//            return this;
//        }
//
//        @Deprecated
//        public interface ICriteriaAdd {
//            /**
//             * This method was generated by MyBatis Generator.
//             * This method corresponds to the database table api_call_logs
//             *
//             * @mbg.generated
//             */
//            Criteria add(Criteria add);
//        }
//    }
//
//    /**
//     * This class was generated by MyBatis Generator.
//     * This class corresponds to the database table api_call_logs
//     *
//     * @mbg.generated
//     */
//    public static class Criterion {
//        private String condition;
//
//        private Object value;
//
//        private Object secondValue;
//
//        private boolean noValue;
//
//        private boolean singleValue;
//
//        private boolean betweenValue;
//
//        private boolean listValue;
//
//        private String typeHandler;
//
//        public String getCondition() {
//            return condition;
//        }
//
//        public Object getValue() {
//            return value;
//        }
//
//        public Object getSecondValue() {
//            return secondValue;
//        }
//
//        public boolean isNoValue() {
//            return noValue;
//        }
//
//        public boolean isSingleValue() {
//            return singleValue;
//        }
//
//        public boolean isBetweenValue() {
//            return betweenValue;
//        }
//
//        public boolean isListValue() {
//            return listValue;
//        }
//
//        public String getTypeHandler() {
//            return typeHandler;
//        }
//
//        protected Criterion(String condition) {
//            super();
//            this.condition = condition;
//            this.typeHandler = null;
//            this.noValue = true;
//        }
//
//        protected Criterion(String condition, Object value, String typeHandler) {
//            super();
//            this.condition = condition;
//            this.value = value;
//            this.typeHandler = typeHandler;
//            if (value instanceof List<?>) {
//                this.listValue = true;
//            } else {
//                this.singleValue = true;
//            }
//        }
//
//        protected Criterion(String condition, Object value) {
//            this(condition, value, null);
//        }
//
//        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
//            super();
//            this.condition = condition;
//            this.value = value;
//            this.secondValue = secondValue;
//            this.typeHandler = typeHandler;
//            this.betweenValue = true;
//        }
//
//        protected Criterion(String condition, Object value, Object secondValue) {
//            this(condition, value, secondValue, null);
//        }
//    }
//
//    public interface ICriteriaWhen {
//        /**
//         * This method was generated by MyBatis Generator.
//         * This method corresponds to the database table api_call_logs
//         *
//         * @mbg.generated
//         */
//        void criteria(Criteria criteria);
//    }
//
//    public interface IExampleWhen {
//        /**
//         * This method was generated by MyBatis Generator.
//         * This method corresponds to the database table api_call_logs
//         *
//         * @mbg.generated
//         */
//        void example(com.supcoder.hub.db.domain.ApiCallLogsExample example);
//    }
//}