//package com.supcoder.system.domain;
//
//import java.time.LocalDateTime;
//import java.util.ArrayList;
//import java.util.List;
//
//public class ApiKeysExample {
//    /**
//     * This field was generated by MyBatis Generator.
//     * This field corresponds to the database table api_keys
//     *
//     * @mbg.generated
//     */
//    protected String orderByClause;
//
//    /**
//     * This field was generated by MyBatis Generator.
//     * This field corresponds to the database table api_keys
//     *
//     * @mbg.generated
//     */
//    protected boolean distinct;
//
//    /**
//     * This field was generated by MyBatis Generator.
//     * This field corresponds to the database table api_keys
//     *
//     * @mbg.generated
//     */
//    protected List<Criteria> oredCriteria;
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table api_keys
//     *
//     * @mbg.generated
//     */
//    public ApiKeysExample() {
//        oredCriteria = new ArrayList<Criteria>();
//    }
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table api_keys
//     *
//     * @mbg.generated
//     */
//    public void setOrderByClause(String orderByClause) {
//        this.orderByClause = orderByClause;
//    }
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table api_keys
//     *
//     * @mbg.generated
//     */
//    public String getOrderByClause() {
//        return orderByClause;
//    }
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table api_keys
//     *
//     * @mbg.generated
//     */
//    public void setDistinct(boolean distinct) {
//        this.distinct = distinct;
//    }
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table api_keys
//     *
//     * @mbg.generated
//     */
//    public boolean isDistinct() {
//        return distinct;
//    }
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table api_keys
//     *
//     * @mbg.generated
//     */
//    public List<Criteria> getOredCriteria() {
//        return oredCriteria;
//    }
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table api_keys
//     *
//     * @mbg.generated
//     */
//    public void or(Criteria criteria) {
//        oredCriteria.add(criteria);
//    }
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table api_keys
//     *
//     * @mbg.generated
//     */
//    public Criteria or() {
//        Criteria criteria = createCriteriaInternal();
//        oredCriteria.add(criteria);
//        return criteria;
//    }
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table api_keys
//     *
//     * @mbg.generated
//     */
//    public ApiKeysExample orderBy(String orderByClause) {
//        this.setOrderByClause(orderByClause);
//        return this;
//    }
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table api_keys
//     *
//     * @mbg.generated
//     */
//    public ApiKeysExample orderBy(String ... orderByClauses) {
//        StringBuffer sb = new StringBuffer();
//        for (int i = 0; i < orderByClauses.length; i++) {
//            sb.append(orderByClauses[i]);
//            if (i < orderByClauses.length - 1) {
//                sb.append(" , ");
//            }
//        }
//        this.setOrderByClause(sb.toString());
//        return this;
//    }
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table api_keys
//     *
//     * @mbg.generated
//     */
//    public Criteria createCriteria() {
//        Criteria criteria = createCriteriaInternal();
//        if (oredCriteria.size() == 0) {
//            oredCriteria.add(criteria);
//        }
//        return criteria;
//    }
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table api_keys
//     *
//     * @mbg.generated
//     */
//    protected Criteria createCriteriaInternal() {
//        Criteria criteria = new Criteria(this);
//        return criteria;
//    }
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table api_keys
//     *
//     * @mbg.generated
//     */
//    public void clear() {
//        oredCriteria.clear();
//        orderByClause = null;
//        distinct = false;
//    }
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table api_keys
//     *
//     * @mbg.generated
//     */
//    public static Criteria newAndCreateCriteria() {
//        ApiKeysExample example = new ApiKeysExample();
//        return example.createCriteria();
//    }
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table api_keys
//     *
//     * @mbg.generated
//     */
//    public ApiKeysExample when(boolean condition, IExampleWhen then) {
//        if (condition) {
//            then.example(this);
//        }
//        return this;
//    }
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table api_keys
//     *
//     * @mbg.generated
//     */
//    public ApiKeysExample when(boolean condition, IExampleWhen then, IExampleWhen otherwise) {
//        if (condition) {
//            then.example(this);
//        } else {
//            otherwise.example(this);
//        }
//        return this;
//    }
//
//    /**
//     * This class was generated by MyBatis Generator.
//     * This class corresponds to the database table api_keys
//     *
//     * @mbg.generated
//     */
//    protected abstract static class GeneratedCriteria {
//        protected List<Criterion> criteria;
//
//        protected GeneratedCriteria() {
//            super();
//            criteria = new ArrayList<Criterion>();
//        }
//
//        public boolean isValid() {
//            return criteria.size() > 0;
//        }
//
//        public List<Criterion> getAllCriteria() {
//            return criteria;
//        }
//
//        public List<Criterion> getCriteria() {
//            return criteria;
//        }
//
//        protected void addCriterion(String condition) {
//            if (condition == null) {
//                throw new RuntimeException("Value for condition cannot be null");
//            }
//            criteria.add(new Criterion(condition));
//        }
//
//        protected void addCriterion(String condition, Object value, String property) {
//            if (value == null) {
//                throw new RuntimeException("Value for " + property + " cannot be null");
//            }
//            criteria.add(new Criterion(condition, value));
//        }
//
//        protected void addCriterion(String condition, Object value1, Object value2, String property) {
//            if (value1 == null || value2 == null) {
//                throw new RuntimeException("Between values for " + property + " cannot be null");
//            }
//            criteria.add(new Criterion(condition, value1, value2));
//        }
//
//        public Criteria andKeyIdIsNull() {
//            addCriterion("key_id is null");
//            return (Criteria) this;
//        }
//
//        public Criteria andKeyIdIsNotNull() {
//            addCriterion("key_id is not null");
//            return (Criteria) this;
//        }
//
//        public Criteria andKeyIdEqualTo(Integer value) {
//            addCriterion("key_id =", value, "keyId");
//            return (Criteria) this;
//        }
//
//        /**
//         * This method was generated by MyBatis Generator.
//         * This method corresponds to the database table api_keys
//         *
//         * @mbg.generated
//         */
//        public Criteria andKeyIdEqualToColumn(ApiKeys.Column column) {
//            addCriterion(new StringBuilder("key_id = ").append(column.getEscapedColumnName()).toString());
//            return (Criteria) this;
//        }
//
//        public Criteria andKeyIdNotEqualTo(Integer value) {
//            addCriterion("key_id <>", value, "keyId");
//            return (Criteria) this;
//        }
//
//        /**
//         * This method was generated by MyBatis Generator.
//         * This method corresponds to the database table api_keys
//         *
//         * @mbg.generated
//         */
//        public Criteria andKeyIdNotEqualToColumn(ApiKeys.Column column) {
//            addCriterion(new StringBuilder("key_id <> ").append(column.getEscapedColumnName()).toString());
//            return (Criteria) this;
//        }
//
//        public Criteria andKeyIdGreaterThan(Integer value) {
//            addCriterion("key_id >", value, "keyId");
//            return (Criteria) this;
//        }
//
//        /**
//         * This method was generated by MyBatis Generator.
//         * This method corresponds to the database table api_keys
//         *
//         * @mbg.generated
//         */
//        public Criteria andKeyIdGreaterThanColumn(ApiKeys.Column column) {
//            addCriterion(new StringBuilder("key_id > ").append(column.getEscapedColumnName()).toString());
//            return (Criteria) this;
//        }
//
//        public Criteria andKeyIdGreaterThanOrEqualTo(Integer value) {
//            addCriterion("key_id >=", value, "keyId");
//            return (Criteria) this;
//        }
//
//        /**
//         * This method was generated by MyBatis Generator.
//         * This method corresponds to the database table api_keys
//         *
//         * @mbg.generated
//         */
//        public Criteria andKeyIdGreaterThanOrEqualToColumn(ApiKeys.Column column) {
//            addCriterion(new StringBuilder("key_id >= ").append(column.getEscapedColumnName()).toString());
//            return (Criteria) this;
//        }
//
//        public Criteria andKeyIdLessThan(Integer value) {
//            addCriterion("key_id <", value, "keyId");
//            return (Criteria) this;
//        }
//
//        /**
//         * This method was generated by MyBatis Generator.
//         * This method corresponds to the database table api_keys
//         *
//         * @mbg.generated
//         */
//        public Criteria andKeyIdLessThanColumn(ApiKeys.Column column) {
//            addCriterion(new StringBuilder("key_id < ").append(column.getEscapedColumnName()).toString());
//            return (Criteria) this;
//        }
//
//        public Criteria andKeyIdLessThanOrEqualTo(Integer value) {
//            addCriterion("key_id <=", value, "keyId");
//            return (Criteria) this;
//        }
//
//        /**
//         * This method was generated by MyBatis Generator.
//         * This method corresponds to the database table api_keys
//         *
//         * @mbg.generated
//         */
//        public Criteria andKeyIdLessThanOrEqualToColumn(ApiKeys.Column column) {
//            addCriterion(new StringBuilder("key_id <= ").append(column.getEscapedColumnName()).toString());
//            return (Criteria) this;
//        }
//
//        public Criteria andKeyIdIn(List<Integer> values) {
//            addCriterion("key_id in", values, "keyId");
//            return (Criteria) this;
//        }
//
//        public Criteria andKeyIdNotIn(List<Integer> values) {
//            addCriterion("key_id not in", values, "keyId");
//            return (Criteria) this;
//        }
//
//        public Criteria andKeyIdBetween(Integer value1, Integer value2) {
//            addCriterion("key_id between", value1, value2, "keyId");
//            return (Criteria) this;
//        }
//
//        public Criteria andKeyIdNotBetween(Integer value1, Integer value2) {
//            addCriterion("key_id not between", value1, value2, "keyId");
//            return (Criteria) this;
//        }
//
//        public Criteria andAccessKeyIsNull() {
//            addCriterion("access_key is null");
//            return (Criteria) this;
//        }
//
//        public Criteria andAccessKeyIsNotNull() {
//            addCriterion("access_key is not null");
//            return (Criteria) this;
//        }
//
//        public Criteria andAccessKeyEqualTo(String value) {
//            addCriterion("access_key =", value, "accessKey");
//            return (Criteria) this;
//        }
//
//        /**
//         * This method was generated by MyBatis Generator.
//         * This method corresponds to the database table api_keys
//         *
//         * @mbg.generated
//         */
//        public Criteria andAccessKeyEqualToColumn(ApiKeys.Column column) {
//            addCriterion(new StringBuilder("access_key = ").append(column.getEscapedColumnName()).toString());
//            return (Criteria) this;
//        }
//
//        public Criteria andAccessKeyNotEqualTo(String value) {
//            addCriterion("access_key <>", value, "accessKey");
//            return (Criteria) this;
//        }
//
//        /**
//         * This method was generated by MyBatis Generator.
//         * This method corresponds to the database table api_keys
//         *
//         * @mbg.generated
//         */
//        public Criteria andAccessKeyNotEqualToColumn(ApiKeys.Column column) {
//            addCriterion(new StringBuilder("access_key <> ").append(column.getEscapedColumnName()).toString());
//            return (Criteria) this;
//        }
//
//        public Criteria andAccessKeyGreaterThan(String value) {
//            addCriterion("access_key >", value, "accessKey");
//            return (Criteria) this;
//        }
//
//        /**
//         * This method was generated by MyBatis Generator.
//         * This method corresponds to the database table api_keys
//         *
//         * @mbg.generated
//         */
//        public Criteria andAccessKeyGreaterThanColumn(ApiKeys.Column column) {
//            addCriterion(new StringBuilder("access_key > ").append(column.getEscapedColumnName()).toString());
//            return (Criteria) this;
//        }
//
//        public Criteria andAccessKeyGreaterThanOrEqualTo(String value) {
//            addCriterion("access_key >=", value, "accessKey");
//            return (Criteria) this;
//        }
//
//        /**
//         * This method was generated by MyBatis Generator.
//         * This method corresponds to the database table api_keys
//         *
//         * @mbg.generated
//         */
//        public Criteria andAccessKeyGreaterThanOrEqualToColumn(ApiKeys.Column column) {
//            addCriterion(new StringBuilder("access_key >= ").append(column.getEscapedColumnName()).toString());
//            return (Criteria) this;
//        }
//
//        public Criteria andAccessKeyLessThan(String value) {
//            addCriterion("access_key <", value, "accessKey");
//            return (Criteria) this;
//        }
//
//        /**
//         * This method was generated by MyBatis Generator.
//         * This method corresponds to the database table api_keys
//         *
//         * @mbg.generated
//         */
//        public Criteria andAccessKeyLessThanColumn(ApiKeys.Column column) {
//            addCriterion(new StringBuilder("access_key < ").append(column.getEscapedColumnName()).toString());
//            return (Criteria) this;
//        }
//
//        public Criteria andAccessKeyLessThanOrEqualTo(String value) {
//            addCriterion("access_key <=", value, "accessKey");
//            return (Criteria) this;
//        }
//
//        /**
//         * This method was generated by MyBatis Generator.
//         * This method corresponds to the database table api_keys
//         *
//         * @mbg.generated
//         */
//        public Criteria andAccessKeyLessThanOrEqualToColumn(ApiKeys.Column column) {
//            addCriterion(new StringBuilder("access_key <= ").append(column.getEscapedColumnName()).toString());
//            return (Criteria) this;
//        }
//
//        public Criteria andAccessKeyLike(String value) {
//            addCriterion("access_key like", value, "accessKey");
//            return (Criteria) this;
//        }
//
//        public Criteria andAccessKeyNotLike(String value) {
//            addCriterion("access_key not like", value, "accessKey");
//            return (Criteria) this;
//        }
//
//        public Criteria andAccessKeyIn(List<String> values) {
//            addCriterion("access_key in", values, "accessKey");
//            return (Criteria) this;
//        }
//
//        public Criteria andAccessKeyNotIn(List<String> values) {
//            addCriterion("access_key not in", values, "accessKey");
//            return (Criteria) this;
//        }
//
//        public Criteria andAccessKeyBetween(String value1, String value2) {
//            addCriterion("access_key between", value1, value2, "accessKey");
//            return (Criteria) this;
//        }
//
//        public Criteria andAccessKeyNotBetween(String value1, String value2) {
//            addCriterion("access_key not between", value1, value2, "accessKey");
//            return (Criteria) this;
//        }
//
//        public Criteria andSecretKeyIsNull() {
//            addCriterion("secret_key is null");
//            return (Criteria) this;
//        }
//
//        public Criteria andSecretKeyIsNotNull() {
//            addCriterion("secret_key is not null");
//            return (Criteria) this;
//        }
//
//        public Criteria andSecretKeyEqualTo(String value) {
//            addCriterion("secret_key =", value, "secretKey");
//            return (Criteria) this;
//        }
//
//        /**
//         * This method was generated by MyBatis Generator.
//         * This method corresponds to the database table api_keys
//         *
//         * @mbg.generated
//         */
//        public Criteria andSecretKeyEqualToColumn(ApiKeys.Column column) {
//            addCriterion(new StringBuilder("secret_key = ").append(column.getEscapedColumnName()).toString());
//            return (Criteria) this;
//        }
//
//        public Criteria andSecretKeyNotEqualTo(String value) {
//            addCriterion("secret_key <>", value, "secretKey");
//            return (Criteria) this;
//        }
//
//        /**
//         * This method was generated by MyBatis Generator.
//         * This method corresponds to the database table api_keys
//         *
//         * @mbg.generated
//         */
//        public Criteria andSecretKeyNotEqualToColumn(ApiKeys.Column column) {
//            addCriterion(new StringBuilder("secret_key <> ").append(column.getEscapedColumnName()).toString());
//            return (Criteria) this;
//        }
//
//        public Criteria andSecretKeyGreaterThan(String value) {
//            addCriterion("secret_key >", value, "secretKey");
//            return (Criteria) this;
//        }
//
//        /**
//         * This method was generated by MyBatis Generator.
//         * This method corresponds to the database table api_keys
//         *
//         * @mbg.generated
//         */
//        public Criteria andSecretKeyGreaterThanColumn(ApiKeys.Column column) {
//            addCriterion(new StringBuilder("secret_key > ").append(column.getEscapedColumnName()).toString());
//            return (Criteria) this;
//        }
//
//        public Criteria andSecretKeyGreaterThanOrEqualTo(String value) {
//            addCriterion("secret_key >=", value, "secretKey");
//            return (Criteria) this;
//        }
//
//        /**
//         * This method was generated by MyBatis Generator.
//         * This method corresponds to the database table api_keys
//         *
//         * @mbg.generated
//         */
//        public Criteria andSecretKeyGreaterThanOrEqualToColumn(ApiKeys.Column column) {
//            addCriterion(new StringBuilder("secret_key >= ").append(column.getEscapedColumnName()).toString());
//            return (Criteria) this;
//        }
//
//        public Criteria andSecretKeyLessThan(String value) {
//            addCriterion("secret_key <", value, "secretKey");
//            return (Criteria) this;
//        }
//
//        /**
//         * This method was generated by MyBatis Generator.
//         * This method corresponds to the database table api_keys
//         *
//         * @mbg.generated
//         */
//        public Criteria andSecretKeyLessThanColumn(ApiKeys.Column column) {
//            addCriterion(new StringBuilder("secret_key < ").append(column.getEscapedColumnName()).toString());
//            return (Criteria) this;
//        }
//
//        public Criteria andSecretKeyLessThanOrEqualTo(String value) {
//            addCriterion("secret_key <=", value, "secretKey");
//            return (Criteria) this;
//        }
//
//        /**
//         * This method was generated by MyBatis Generator.
//         * This method corresponds to the database table api_keys
//         *
//         * @mbg.generated
//         */
//        public Criteria andSecretKeyLessThanOrEqualToColumn(ApiKeys.Column column) {
//            addCriterion(new StringBuilder("secret_key <= ").append(column.getEscapedColumnName()).toString());
//            return (Criteria) this;
//        }
//
//        public Criteria andSecretKeyLike(String value) {
//            addCriterion("secret_key like", value, "secretKey");
//            return (Criteria) this;
//        }
//
//        public Criteria andSecretKeyNotLike(String value) {
//            addCriterion("secret_key not like", value, "secretKey");
//            return (Criteria) this;
//        }
//
//        public Criteria andSecretKeyIn(List<String> values) {
//            addCriterion("secret_key in", values, "secretKey");
//            return (Criteria) this;
//        }
//
//        public Criteria andSecretKeyNotIn(List<String> values) {
//            addCriterion("secret_key not in", values, "secretKey");
//            return (Criteria) this;
//        }
//
//        public Criteria andSecretKeyBetween(String value1, String value2) {
//            addCriterion("secret_key between", value1, value2, "secretKey");
//            return (Criteria) this;
//        }
//
//        public Criteria andSecretKeyNotBetween(String value1, String value2) {
//            addCriterion("secret_key not between", value1, value2, "secretKey");
//            return (Criteria) this;
//        }
//
//        public Criteria andUsernameIsNull() {
//            addCriterion("username is null");
//            return (Criteria) this;
//        }
//
//        public Criteria andUsernameIsNotNull() {
//            addCriterion("username is not null");
//            return (Criteria) this;
//        }
//
//        public Criteria andUsernameEqualTo(String value) {
//            addCriterion("username =", value, "username");
//            return (Criteria) this;
//        }
//
//        /**
//         * This method was generated by MyBatis Generator.
//         * This method corresponds to the database table api_keys
//         *
//         * @mbg.generated
//         */
//        public Criteria andUsernameEqualToColumn(ApiKeys.Column column) {
//            addCriterion(new StringBuilder("username = ").append(column.getEscapedColumnName()).toString());
//            return (Criteria) this;
//        }
//
//        public Criteria andUsernameNotEqualTo(String value) {
//            addCriterion("username <>", value, "username");
//            return (Criteria) this;
//        }
//
//        /**
//         * This method was generated by MyBatis Generator.
//         * This method corresponds to the database table api_keys
//         *
//         * @mbg.generated
//         */
//        public Criteria andUsernameNotEqualToColumn(ApiKeys.Column column) {
//            addCriterion(new StringBuilder("username <> ").append(column.getEscapedColumnName()).toString());
//            return (Criteria) this;
//        }
//
//        public Criteria andUsernameGreaterThan(String value) {
//            addCriterion("username >", value, "username");
//            return (Criteria) this;
//        }
//
//        /**
//         * This method was generated by MyBatis Generator.
//         * This method corresponds to the database table api_keys
//         *
//         * @mbg.generated
//         */
//        public Criteria andUsernameGreaterThanColumn(ApiKeys.Column column) {
//            addCriterion(new StringBuilder("username > ").append(column.getEscapedColumnName()).toString());
//            return (Criteria) this;
//        }
//
//        public Criteria andUsernameGreaterThanOrEqualTo(String value) {
//            addCriterion("username >=", value, "username");
//            return (Criteria) this;
//        }
//
//        /**
//         * This method was generated by MyBatis Generator.
//         * This method corresponds to the database table api_keys
//         *
//         * @mbg.generated
//         */
//        public Criteria andUsernameGreaterThanOrEqualToColumn(ApiKeys.Column column) {
//            addCriterion(new StringBuilder("username >= ").append(column.getEscapedColumnName()).toString());
//            return (Criteria) this;
//        }
//
//        public Criteria andUsernameLessThan(String value) {
//            addCriterion("username <", value, "username");
//            return (Criteria) this;
//        }
//
//        /**
//         * This method was generated by MyBatis Generator.
//         * This method corresponds to the database table api_keys
//         *
//         * @mbg.generated
//         */
//        public Criteria andUsernameLessThanColumn(ApiKeys.Column column) {
//            addCriterion(new StringBuilder("username < ").append(column.getEscapedColumnName()).toString());
//            return (Criteria) this;
//        }
//
//        public Criteria andUsernameLessThanOrEqualTo(String value) {
//            addCriterion("username <=", value, "username");
//            return (Criteria) this;
//        }
//
//        /**
//         * This method was generated by MyBatis Generator.
//         * This method corresponds to the database table api_keys
//         *
//         * @mbg.generated
//         */
//        public Criteria andUsernameLessThanOrEqualToColumn(ApiKeys.Column column) {
//            addCriterion(new StringBuilder("username <= ").append(column.getEscapedColumnName()).toString());
//            return (Criteria) this;
//        }
//
//        public Criteria andUsernameLike(String value) {
//            addCriterion("username like", value, "username");
//            return (Criteria) this;
//        }
//
//        public Criteria andUsernameNotLike(String value) {
//            addCriterion("username not like", value, "username");
//            return (Criteria) this;
//        }
//
//        public Criteria andUsernameIn(List<String> values) {
//            addCriterion("username in", values, "username");
//            return (Criteria) this;
//        }
//
//        public Criteria andUsernameNotIn(List<String> values) {
//            addCriterion("username not in", values, "username");
//            return (Criteria) this;
//        }
//
//        public Criteria andUsernameBetween(String value1, String value2) {
//            addCriterion("username between", value1, value2, "username");
//            return (Criteria) this;
//        }
//
//        public Criteria andUsernameNotBetween(String value1, String value2) {
//            addCriterion("username not between", value1, value2, "username");
//            return (Criteria) this;
//        }
//
//        public Criteria andStatusIsNull() {
//            addCriterion("`status` is null");
//            return (Criteria) this;
//        }
//
//        public Criteria andStatusIsNotNull() {
//            addCriterion("`status` is not null");
//            return (Criteria) this;
//        }
//
//        public Criteria andStatusEqualTo(String value) {
//            addCriterion("`status` =", value, "status");
//            return (Criteria) this;
//        }
//
//        /**
//         * This method was generated by MyBatis Generator.
//         * This method corresponds to the database table api_keys
//         *
//         * @mbg.generated
//         */
//        public Criteria andStatusEqualToColumn(ApiKeys.Column column) {
//            addCriterion(new StringBuilder("`status` = ").append(column.getEscapedColumnName()).toString());
//            return (Criteria) this;
//        }
//
//        public Criteria andStatusNotEqualTo(String value) {
//            addCriterion("`status` <>", value, "status");
//            return (Criteria) this;
//        }
//
//        /**
//         * This method was generated by MyBatis Generator.
//         * This method corresponds to the database table api_keys
//         *
//         * @mbg.generated
//         */
//        public Criteria andStatusNotEqualToColumn(ApiKeys.Column column) {
//            addCriterion(new StringBuilder("`status` <> ").append(column.getEscapedColumnName()).toString());
//            return (Criteria) this;
//        }
//
//        public Criteria andStatusGreaterThan(String value) {
//            addCriterion("`status` >", value, "status");
//            return (Criteria) this;
//        }
//
//        /**
//         * This method was generated by MyBatis Generator.
//         * This method corresponds to the database table api_keys
//         *
//         * @mbg.generated
//         */
//        public Criteria andStatusGreaterThanColumn(ApiKeys.Column column) {
//            addCriterion(new StringBuilder("`status` > ").append(column.getEscapedColumnName()).toString());
//            return (Criteria) this;
//        }
//
//        public Criteria andStatusGreaterThanOrEqualTo(String value) {
//            addCriterion("`status` >=", value, "status");
//            return (Criteria) this;
//        }
//
//        /**
//         * This method was generated by MyBatis Generator.
//         * This method corresponds to the database table api_keys
//         *
//         * @mbg.generated
//         */
//        public Criteria andStatusGreaterThanOrEqualToColumn(ApiKeys.Column column) {
//            addCriterion(new StringBuilder("`status` >= ").append(column.getEscapedColumnName()).toString());
//            return (Criteria) this;
//        }
//
//        public Criteria andStatusLessThan(String value) {
//            addCriterion("`status` <", value, "status");
//            return (Criteria) this;
//        }
//
//        /**
//         * This method was generated by MyBatis Generator.
//         * This method corresponds to the database table api_keys
//         *
//         * @mbg.generated
//         */
//        public Criteria andStatusLessThanColumn(ApiKeys.Column column) {
//            addCriterion(new StringBuilder("`status` < ").append(column.getEscapedColumnName()).toString());
//            return (Criteria) this;
//        }
//
//        public Criteria andStatusLessThanOrEqualTo(String value) {
//            addCriterion("`status` <=", value, "status");
//            return (Criteria) this;
//        }
//
//        /**
//         * This method was generated by MyBatis Generator.
//         * This method corresponds to the database table api_keys
//         *
//         * @mbg.generated
//         */
//        public Criteria andStatusLessThanOrEqualToColumn(ApiKeys.Column column) {
//            addCriterion(new StringBuilder("`status` <= ").append(column.getEscapedColumnName()).toString());
//            return (Criteria) this;
//        }
//
//        public Criteria andStatusLike(String value) {
//            addCriterion("`status` like", value, "status");
//            return (Criteria) this;
//        }
//
//        public Criteria andStatusNotLike(String value) {
//            addCriterion("`status` not like", value, "status");
//            return (Criteria) this;
//        }
//
//        public Criteria andStatusIn(List<String> values) {
//            addCriterion("`status` in", values, "status");
//            return (Criteria) this;
//        }
//
//        public Criteria andStatusNotIn(List<String> values) {
//            addCriterion("`status` not in", values, "status");
//            return (Criteria) this;
//        }
//
//        public Criteria andStatusBetween(String value1, String value2) {
//            addCriterion("`status` between", value1, value2, "status");
//            return (Criteria) this;
//        }
//
//        public Criteria andStatusNotBetween(String value1, String value2) {
//            addCriterion("`status` not between", value1, value2, "status");
//            return (Criteria) this;
//        }
//
//        public Criteria andCreationDateIsNull() {
//            addCriterion("creation_date is null");
//            return (Criteria) this;
//        }
//
//        public Criteria andCreationDateIsNotNull() {
//            addCriterion("creation_date is not null");
//            return (Criteria) this;
//        }
//
//        public Criteria andCreationDateEqualTo(LocalDateTime value) {
//            addCriterion("creation_date =", value, "creationDate");
//            return (Criteria) this;
//        }
//
//        /**
//         * This method was generated by MyBatis Generator.
//         * This method corresponds to the database table api_keys
//         *
//         * @mbg.generated
//         */
//        public Criteria andCreationDateEqualToColumn(ApiKeys.Column column) {
//            addCriterion(new StringBuilder("creation_date = ").append(column.getEscapedColumnName()).toString());
//            return (Criteria) this;
//        }
//
//        public Criteria andCreationDateNotEqualTo(LocalDateTime value) {
//            addCriterion("creation_date <>", value, "creationDate");
//            return (Criteria) this;
//        }
//
//        /**
//         * This method was generated by MyBatis Generator.
//         * This method corresponds to the database table api_keys
//         *
//         * @mbg.generated
//         */
//        public Criteria andCreationDateNotEqualToColumn(ApiKeys.Column column) {
//            addCriterion(new StringBuilder("creation_date <> ").append(column.getEscapedColumnName()).toString());
//            return (Criteria) this;
//        }
//
//        public Criteria andCreationDateGreaterThan(LocalDateTime value) {
//            addCriterion("creation_date >", value, "creationDate");
//            return (Criteria) this;
//        }
//
//        /**
//         * This method was generated by MyBatis Generator.
//         * This method corresponds to the database table api_keys
//         *
//         * @mbg.generated
//         */
//        public Criteria andCreationDateGreaterThanColumn(ApiKeys.Column column) {
//            addCriterion(new StringBuilder("creation_date > ").append(column.getEscapedColumnName()).toString());
//            return (Criteria) this;
//        }
//
//        public Criteria andCreationDateGreaterThanOrEqualTo(LocalDateTime value) {
//            addCriterion("creation_date >=", value, "creationDate");
//            return (Criteria) this;
//        }
//
//        /**
//         * This method was generated by MyBatis Generator.
//         * This method corresponds to the database table api_keys
//         *
//         * @mbg.generated
//         */
//        public Criteria andCreationDateGreaterThanOrEqualToColumn(ApiKeys.Column column) {
//            addCriterion(new StringBuilder("creation_date >= ").append(column.getEscapedColumnName()).toString());
//            return (Criteria) this;
//        }
//
//        public Criteria andCreationDateLessThan(LocalDateTime value) {
//            addCriterion("creation_date <", value, "creationDate");
//            return (Criteria) this;
//        }
//
//        /**
//         * This method was generated by MyBatis Generator.
//         * This method corresponds to the database table api_keys
//         *
//         * @mbg.generated
//         */
//        public Criteria andCreationDateLessThanColumn(ApiKeys.Column column) {
//            addCriterion(new StringBuilder("creation_date < ").append(column.getEscapedColumnName()).toString());
//            return (Criteria) this;
//        }
//
//        public Criteria andCreationDateLessThanOrEqualTo(LocalDateTime value) {
//            addCriterion("creation_date <=", value, "creationDate");
//            return (Criteria) this;
//        }
//
//        /**
//         * This method was generated by MyBatis Generator.
//         * This method corresponds to the database table api_keys
//         *
//         * @mbg.generated
//         */
//        public Criteria andCreationDateLessThanOrEqualToColumn(ApiKeys.Column column) {
//            addCriterion(new StringBuilder("creation_date <= ").append(column.getEscapedColumnName()).toString());
//            return (Criteria) this;
//        }
//
//        public Criteria andCreationDateIn(List<LocalDateTime> values) {
//            addCriterion("creation_date in", values, "creationDate");
//            return (Criteria) this;
//        }
//
//        public Criteria andCreationDateNotIn(List<LocalDateTime> values) {
//            addCriterion("creation_date not in", values, "creationDate");
//            return (Criteria) this;
//        }
//
//        public Criteria andCreationDateBetween(LocalDateTime value1, LocalDateTime value2) {
//            addCriterion("creation_date between", value1, value2, "creationDate");
//            return (Criteria) this;
//        }
//
//        public Criteria andCreationDateNotBetween(LocalDateTime value1, LocalDateTime value2) {
//            addCriterion("creation_date not between", value1, value2, "creationDate");
//            return (Criteria) this;
//        }
//
//        public Criteria andLastUsedDateIsNull() {
//            addCriterion("last_used_date is null");
//            return (Criteria) this;
//        }
//
//        public Criteria andLastUsedDateIsNotNull() {
//            addCriterion("last_used_date is not null");
//            return (Criteria) this;
//        }
//
//        public Criteria andLastUsedDateEqualTo(LocalDateTime value) {
//            addCriterion("last_used_date =", value, "lastUsedDate");
//            return (Criteria) this;
//        }
//
//        /**
//         * This method was generated by MyBatis Generator.
//         * This method corresponds to the database table api_keys
//         *
//         * @mbg.generated
//         */
//        public Criteria andLastUsedDateEqualToColumn(ApiKeys.Column column) {
//            addCriterion(new StringBuilder("last_used_date = ").append(column.getEscapedColumnName()).toString());
//            return (Criteria) this;
//        }
//
//        public Criteria andLastUsedDateNotEqualTo(LocalDateTime value) {
//            addCriterion("last_used_date <>", value, "lastUsedDate");
//            return (Criteria) this;
//        }
//
//        /**
//         * This method was generated by MyBatis Generator.
//         * This method corresponds to the database table api_keys
//         *
//         * @mbg.generated
//         */
//        public Criteria andLastUsedDateNotEqualToColumn(ApiKeys.Column column) {
//            addCriterion(new StringBuilder("last_used_date <> ").append(column.getEscapedColumnName()).toString());
//            return (Criteria) this;
//        }
//
//        public Criteria andLastUsedDateGreaterThan(LocalDateTime value) {
//            addCriterion("last_used_date >", value, "lastUsedDate");
//            return (Criteria) this;
//        }
//
//        /**
//         * This method was generated by MyBatis Generator.
//         * This method corresponds to the database table api_keys
//         *
//         * @mbg.generated
//         */
//        public Criteria andLastUsedDateGreaterThanColumn(ApiKeys.Column column) {
//            addCriterion(new StringBuilder("last_used_date > ").append(column.getEscapedColumnName()).toString());
//            return (Criteria) this;
//        }
//
//        public Criteria andLastUsedDateGreaterThanOrEqualTo(LocalDateTime value) {
//            addCriterion("last_used_date >=", value, "lastUsedDate");
//            return (Criteria) this;
//        }
//
//        /**
//         * This method was generated by MyBatis Generator.
//         * This method corresponds to the database table api_keys
//         *
//         * @mbg.generated
//         */
//        public Criteria andLastUsedDateGreaterThanOrEqualToColumn(ApiKeys.Column column) {
//            addCriterion(new StringBuilder("last_used_date >= ").append(column.getEscapedColumnName()).toString());
//            return (Criteria) this;
//        }
//
//        public Criteria andLastUsedDateLessThan(LocalDateTime value) {
//            addCriterion("last_used_date <", value, "lastUsedDate");
//            return (Criteria) this;
//        }
//
//        /**
//         * This method was generated by MyBatis Generator.
//         * This method corresponds to the database table api_keys
//         *
//         * @mbg.generated
//         */
//        public Criteria andLastUsedDateLessThanColumn(ApiKeys.Column column) {
//            addCriterion(new StringBuilder("last_used_date < ").append(column.getEscapedColumnName()).toString());
//            return (Criteria) this;
//        }
//
//        public Criteria andLastUsedDateLessThanOrEqualTo(LocalDateTime value) {
//            addCriterion("last_used_date <=", value, "lastUsedDate");
//            return (Criteria) this;
//        }
//
//        /**
//         * This method was generated by MyBatis Generator.
//         * This method corresponds to the database table api_keys
//         *
//         * @mbg.generated
//         */
//        public Criteria andLastUsedDateLessThanOrEqualToColumn(ApiKeys.Column column) {
//            addCriterion(new StringBuilder("last_used_date <= ").append(column.getEscapedColumnName()).toString());
//            return (Criteria) this;
//        }
//
//        public Criteria andLastUsedDateIn(List<LocalDateTime> values) {
//            addCriterion("last_used_date in", values, "lastUsedDate");
//            return (Criteria) this;
//        }
//
//        public Criteria andLastUsedDateNotIn(List<LocalDateTime> values) {
//            addCriterion("last_used_date not in", values, "lastUsedDate");
//            return (Criteria) this;
//        }
//
//        public Criteria andLastUsedDateBetween(LocalDateTime value1, LocalDateTime value2) {
//            addCriterion("last_used_date between", value1, value2, "lastUsedDate");
//            return (Criteria) this;
//        }
//
//        public Criteria andLastUsedDateNotBetween(LocalDateTime value1, LocalDateTime value2) {
//            addCriterion("last_used_date not between", value1, value2, "lastUsedDate");
//            return (Criteria) this;
//        }
//
//        public Criteria andServiceIsNull() {
//            addCriterion("service is null");
//            return (Criteria) this;
//        }
//
//        public Criteria andServiceIsNotNull() {
//            addCriterion("service is not null");
//            return (Criteria) this;
//        }
//
//        public Criteria andServiceEqualTo(String value) {
//            addCriterion("service =", value, "service");
//            return (Criteria) this;
//        }
//
//        /**
//         * This method was generated by MyBatis Generator.
//         * This method corresponds to the database table api_keys
//         *
//         * @mbg.generated
//         */
//        public Criteria andServiceEqualToColumn(ApiKeys.Column column) {
//            addCriterion(new StringBuilder("service = ").append(column.getEscapedColumnName()).toString());
//            return (Criteria) this;
//        }
//
//        public Criteria andServiceNotEqualTo(String value) {
//            addCriterion("service <>", value, "service");
//            return (Criteria) this;
//        }
//
//        /**
//         * This method was generated by MyBatis Generator.
//         * This method corresponds to the database table api_keys
//         *
//         * @mbg.generated
//         */
//        public Criteria andServiceNotEqualToColumn(ApiKeys.Column column) {
//            addCriterion(new StringBuilder("service <> ").append(column.getEscapedColumnName()).toString());
//            return (Criteria) this;
//        }
//
//        public Criteria andServiceGreaterThan(String value) {
//            addCriterion("service >", value, "service");
//            return (Criteria) this;
//        }
//
//        /**
//         * This method was generated by MyBatis Generator.
//         * This method corresponds to the database table api_keys
//         *
//         * @mbg.generated
//         */
//        public Criteria andServiceGreaterThanColumn(ApiKeys.Column column) {
//            addCriterion(new StringBuilder("service > ").append(column.getEscapedColumnName()).toString());
//            return (Criteria) this;
//        }
//
//        public Criteria andServiceGreaterThanOrEqualTo(String value) {
//            addCriterion("service >=", value, "service");
//            return (Criteria) this;
//        }
//
//        /**
//         * This method was generated by MyBatis Generator.
//         * This method corresponds to the database table api_keys
//         *
//         * @mbg.generated
//         */
//        public Criteria andServiceGreaterThanOrEqualToColumn(ApiKeys.Column column) {
//            addCriterion(new StringBuilder("service >= ").append(column.getEscapedColumnName()).toString());
//            return (Criteria) this;
//        }
//
//        public Criteria andServiceLessThan(String value) {
//            addCriterion("service <", value, "service");
//            return (Criteria) this;
//        }
//
//        /**
//         * This method was generated by MyBatis Generator.
//         * This method corresponds to the database table api_keys
//         *
//         * @mbg.generated
//         */
//        public Criteria andServiceLessThanColumn(ApiKeys.Column column) {
//            addCriterion(new StringBuilder("service < ").append(column.getEscapedColumnName()).toString());
//            return (Criteria) this;
//        }
//
//        public Criteria andServiceLessThanOrEqualTo(String value) {
//            addCriterion("service <=", value, "service");
//            return (Criteria) this;
//        }
//
//        /**
//         * This method was generated by MyBatis Generator.
//         * This method corresponds to the database table api_keys
//         *
//         * @mbg.generated
//         */
//        public Criteria andServiceLessThanOrEqualToColumn(ApiKeys.Column column) {
//            addCriterion(new StringBuilder("service <= ").append(column.getEscapedColumnName()).toString());
//            return (Criteria) this;
//        }
//
//        public Criteria andServiceLike(String value) {
//            addCriterion("service like", value, "service");
//            return (Criteria) this;
//        }
//
//        public Criteria andServiceNotLike(String value) {
//            addCriterion("service not like", value, "service");
//            return (Criteria) this;
//        }
//
//        public Criteria andServiceIn(List<String> values) {
//            addCriterion("service in", values, "service");
//            return (Criteria) this;
//        }
//
//        public Criteria andServiceNotIn(List<String> values) {
//            addCriterion("service not in", values, "service");
//            return (Criteria) this;
//        }
//
//        public Criteria andServiceBetween(String value1, String value2) {
//            addCriterion("service between", value1, value2, "service");
//            return (Criteria) this;
//        }
//
//        public Criteria andServiceNotBetween(String value1, String value2) {
//            addCriterion("service not between", value1, value2, "service");
//            return (Criteria) this;
//        }
//
//        public Criteria andPermissionsIsNull() {
//            addCriterion("permissions is null");
//            return (Criteria) this;
//        }
//
//        public Criteria andPermissionsIsNotNull() {
//            addCriterion("permissions is not null");
//            return (Criteria) this;
//        }
//
//        public Criteria andPermissionsEqualTo(String value) {
//            addCriterion("permissions =", value, "permissions");
//            return (Criteria) this;
//        }
//
//        /**
//         * This method was generated by MyBatis Generator.
//         * This method corresponds to the database table api_keys
//         *
//         * @mbg.generated
//         */
//        public Criteria andPermissionsEqualToColumn(ApiKeys.Column column) {
//            addCriterion(new StringBuilder("permissions = ").append(column.getEscapedColumnName()).toString());
//            return (Criteria) this;
//        }
//
//        public Criteria andPermissionsNotEqualTo(String value) {
//            addCriterion("permissions <>", value, "permissions");
//            return (Criteria) this;
//        }
//
//        /**
//         * This method was generated by MyBatis Generator.
//         * This method corresponds to the database table api_keys
//         *
//         * @mbg.generated
//         */
//        public Criteria andPermissionsNotEqualToColumn(ApiKeys.Column column) {
//            addCriterion(new StringBuilder("permissions <> ").append(column.getEscapedColumnName()).toString());
//            return (Criteria) this;
//        }
//
//        public Criteria andPermissionsGreaterThan(String value) {
//            addCriterion("permissions >", value, "permissions");
//            return (Criteria) this;
//        }
//
//        /**
//         * This method was generated by MyBatis Generator.
//         * This method corresponds to the database table api_keys
//         *
//         * @mbg.generated
//         */
//        public Criteria andPermissionsGreaterThanColumn(ApiKeys.Column column) {
//            addCriterion(new StringBuilder("permissions > ").append(column.getEscapedColumnName()).toString());
//            return (Criteria) this;
//        }
//
//        public Criteria andPermissionsGreaterThanOrEqualTo(String value) {
//            addCriterion("permissions >=", value, "permissions");
//            return (Criteria) this;
//        }
//
//        /**
//         * This method was generated by MyBatis Generator.
//         * This method corresponds to the database table api_keys
//         *
//         * @mbg.generated
//         */
//        public Criteria andPermissionsGreaterThanOrEqualToColumn(ApiKeys.Column column) {
//            addCriterion(new StringBuilder("permissions >= ").append(column.getEscapedColumnName()).toString());
//            return (Criteria) this;
//        }
//
//        public Criteria andPermissionsLessThan(String value) {
//            addCriterion("permissions <", value, "permissions");
//            return (Criteria) this;
//        }
//
//        /**
//         * This method was generated by MyBatis Generator.
//         * This method corresponds to the database table api_keys
//         *
//         * @mbg.generated
//         */
//        public Criteria andPermissionsLessThanColumn(ApiKeys.Column column) {
//            addCriterion(new StringBuilder("permissions < ").append(column.getEscapedColumnName()).toString());
//            return (Criteria) this;
//        }
//
//        public Criteria andPermissionsLessThanOrEqualTo(String value) {
//            addCriterion("permissions <=", value, "permissions");
//            return (Criteria) this;
//        }
//
//        /**
//         * This method was generated by MyBatis Generator.
//         * This method corresponds to the database table api_keys
//         *
//         * @mbg.generated
//         */
//        public Criteria andPermissionsLessThanOrEqualToColumn(ApiKeys.Column column) {
//            addCriterion(new StringBuilder("permissions <= ").append(column.getEscapedColumnName()).toString());
//            return (Criteria) this;
//        }
//
//        public Criteria andPermissionsLike(String value) {
//            addCriterion("permissions like", value, "permissions");
//            return (Criteria) this;
//        }
//
//        public Criteria andPermissionsNotLike(String value) {
//            addCriterion("permissions not like", value, "permissions");
//            return (Criteria) this;
//        }
//
//        public Criteria andPermissionsIn(List<String> values) {
//            addCriterion("permissions in", values, "permissions");
//            return (Criteria) this;
//        }
//
//        public Criteria andPermissionsNotIn(List<String> values) {
//            addCriterion("permissions not in", values, "permissions");
//            return (Criteria) this;
//        }
//
//        public Criteria andPermissionsBetween(String value1, String value2) {
//            addCriterion("permissions between", value1, value2, "permissions");
//            return (Criteria) this;
//        }
//
//        public Criteria andPermissionsNotBetween(String value1, String value2) {
//            addCriterion("permissions not between", value1, value2, "permissions");
//            return (Criteria) this;
//        }
//    }
//
//    /**
//     * This class was generated by MyBatis Generator.
//     * This class corresponds to the database table api_keys
//     *
//     * @mbg.generated do_not_delete_during_merge
//     */
//    public static class Criteria extends GeneratedCriteria {
//        /**
//         * This field was generated by MyBatis Generator.
//         * This field corresponds to the database table api_keys
//         *
//         * @mbg.generated
//         */
//        private ApiKeysExample example;
//
//        /**
//         * This method was generated by MyBatis Generator.
//         * This method corresponds to the database table api_keys
//         *
//         * @mbg.generated
//         */
//        protected Criteria(ApiKeysExample example) {
//            super();
//            this.example = example;
//        }
//
//        /**
//         * This method was generated by MyBatis Generator.
//         * This method corresponds to the database table api_keys
//         *
//         * @mbg.generated
//         */
//        public ApiKeysExample example() {
//            return this.example;
//        }
//
//        /**
//         * This method was generated by MyBatis Generator.
//         * This method corresponds to the database table api_keys
//         *
//         * @mbg.generated
//         */
//        @Deprecated
//        public Criteria andIf(boolean ifAdd, ICriteriaAdd add) {
//            if (ifAdd) {
//                add.add(this);
//            }
//            return this;
//        }
//
//        /**
//         * This method was generated by MyBatis Generator.
//         * This method corresponds to the database table api_keys
//         *
//         * @mbg.generated
//         */
//        public Criteria when(boolean condition, ICriteriaWhen then) {
//            if (condition) {
//                then.criteria(this);
//            }
//            return this;
//        }
//
//        /**
//         * This method was generated by MyBatis Generator.
//         * This method corresponds to the database table api_keys
//         *
//         * @mbg.generated
//         */
//        public Criteria when(boolean condition, ICriteriaWhen then, ICriteriaWhen otherwise) {
//            if (condition) {
//                then.criteria(this);
//            } else {
//                otherwise.criteria(this);
//            }
//            return this;
//        }
//
//        @Deprecated
//        public interface ICriteriaAdd {
//            /**
//             * This method was generated by MyBatis Generator.
//             * This method corresponds to the database table api_keys
//             *
//             * @mbg.generated
//             */
//            Criteria add(Criteria add);
//        }
//    }
//
//    /**
//     * This class was generated by MyBatis Generator.
//     * This class corresponds to the database table api_keys
//     *
//     * @mbg.generated
//     */
//    public static class Criterion {
//        private String condition;
//
//        private Object value;
//
//        private Object secondValue;
//
//        private boolean noValue;
//
//        private boolean singleValue;
//
//        private boolean betweenValue;
//
//        private boolean listValue;
//
//        private String typeHandler;
//
//        public String getCondition() {
//            return condition;
//        }
//
//        public Object getValue() {
//            return value;
//        }
//
//        public Object getSecondValue() {
//            return secondValue;
//        }
//
//        public boolean isNoValue() {
//            return noValue;
//        }
//
//        public boolean isSingleValue() {
//            return singleValue;
//        }
//
//        public boolean isBetweenValue() {
//            return betweenValue;
//        }
//
//        public boolean isListValue() {
//            return listValue;
//        }
//
//        public String getTypeHandler() {
//            return typeHandler;
//        }
//
//        protected Criterion(String condition) {
//            super();
//            this.condition = condition;
//            this.typeHandler = null;
//            this.noValue = true;
//        }
//
//        protected Criterion(String condition, Object value, String typeHandler) {
//            super();
//            this.condition = condition;
//            this.value = value;
//            this.typeHandler = typeHandler;
//            if (value instanceof List<?>) {
//                this.listValue = true;
//            } else {
//                this.singleValue = true;
//            }
//        }
//
//        protected Criterion(String condition, Object value) {
//            this(condition, value, null);
//        }
//
//        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
//            super();
//            this.condition = condition;
//            this.value = value;
//            this.secondValue = secondValue;
//            this.typeHandler = typeHandler;
//            this.betweenValue = true;
//        }
//
//        protected Criterion(String condition, Object value, Object secondValue) {
//            this(condition, value, secondValue, null);
//        }
//    }
//
//    public interface ICriteriaWhen {
//        /**
//         * This method was generated by MyBatis Generator.
//         * This method corresponds to the database table api_keys
//         *
//         * @mbg.generated
//         */
//        void criteria(Criteria criteria);
//    }
//
//    public interface IExampleWhen {
//        /**
//         * This method was generated by MyBatis Generator.
//         * This method corresponds to the database table api_keys
//         *
//         * @mbg.generated
//         */
//        void example(com.supcoder.hub.db.domain.ApiKeysExample example);
//    }
//}